{{- if .Values.webhook.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "promethix-cloudflare-tunnel-operator.name" . }}-webhook
  namespace: {{ include "promethix-cloudflare-tunnel-operator.namespace" . }}
spec:
  secretName: {{ .Values.webhook.certificate.secretName }}
  issuerRef:
    name: {{ include "promethix-cloudflare-tunnel-operator.webhookIssuerName" . | quote }}
    kind: {{ .Values.webhook.certificate.issuerRef.kind | quote }}
    group: {{ .Values.webhook.certificate.issuerRef.group | quote }}
  dnsNames:
    - {{ include "promethix-cloudflare-tunnel-operator.name" . }}.{{ include "promethix-cloudflare-tunnel-operator.namespace" . }}.svc
    - {{ include "promethix-cloudflare-tunnel-operator.name" . }}.{{ include "promethix-cloudflare-tunnel-operator.namespace" . }}.svc.cluster.local
{{- end }}
