apiVersion: v1
kind: Service
metadata:
  name: {{ include "promethix-cloudflare-tunnel-operator.name" . }}
  namespace: {{ include "promethix-cloudflare-tunnel-operator.namespace" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "promethix-cloudflare-tunnel-operator.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- if .Values.webhook.enabled }}
    - name: webhook
      port: {{ .Values.webhook.port }}
      targetPort: webhook
{{- end }}
