{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "promethix-cloudflare-tunnel-operator.serviceAccountName" . }}
  namespace: {{ include "promethix-cloudflare-tunnel-operator.namespace" . }}
{{- end }}
